#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

#bspc monitor -d "I" "II" "III"
#bspc monitor -d I II III
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            4
#bspc config focused_border_color    "#83a598"
bspc config focused_border_color    "#e6b05a"
bspc config normal_border_color     "#454849"
bspc config window_gap              4
#bspc config top_padding             30

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
